platform :ios, '13.0'

target 'Todoey' do
  
  use_frameworks!

  # Pods for Todoey

pod 'RealmSwift', '~> 10.54.1'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git',
:branch => 'swift5'

end
